# 配置服务端口号
server:
  port: 8501

# 配置数据库连接信息
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.14.250:13306/db_warehouse?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 19981213Jt
  # Redis的相关配置
  data:
    redis:
      host: 117.72.14.250
      port: 16379

# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml

# 自定义配置
minio:
  endpointUrl: http://117.72.14.250:9001
  accessKey: admin
  secreKey: admin123456
  bucketName: warehousex-bucket